name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir
        run: echo "::set-output name=dir::$(pnpm cache dir)"

      - name: Restore pnpm cache
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Install Dependencies
        run: pnpm install

      - name: GraphQL Codegen
        run: pnpm codegen

      - name: Lint
        run: pnpm lint

      - name: Prettier Check
        run: pnpm prettier:check

      - name: Typescript typecheck
        run: pnpm typecheck

      - name: Build Lenster
        run: pnpm build
